"""
main.py
=================================================================
Entry point for the candle-labeler app.

BEFORE RUNNING THIS FILE FOR THE FIRST TIME:
    Run setup_data.py once. It builds data/xauusd_1min.csv (the
    candle file this script reads) and creates my_data.csv (the file
    this script appends your decisions to). See README.md.

WHAT THIS FILE DOES, EACH LOOP ITERATION ("batch"):
    1. Picks one random candle from the full history.
    2. Spawns 6 separate browser-based chart windows (via chart_app.py),
       each showing a different lookback window ending at that same
       candle (300, 200, 100, 50, 20, and 10 candles back).
    3. Waits until you've clicked Buy / Neutral / Sell in all 6 windows.
    4. Appends your 6 decisions as one row to my_data.csv.
    5. Feeds your decisions to the online model (model_agent.py) for a
       training step, and prints what the model would have predicted
       for comparison.
    6. Asks whether to run another batch or quit.

WARNING - kill_other_python_processes():
    This function kills every OTHER python process on your machine
    (not just ones related to this project) at the start of each loop
    iteration, to make sure old chart windows/ports don't linger. Do
    not run this on a machine where you have other important Python
    processes running - they will be terminated.
=================================================================
"""

import pandas as pd
import random
import time
import os
import psutil
import multiprocessing
from chart_app import show_candles
from model_agent import OnlineModelAgent


def kill_other_python_processes():
    """
    Kill every running python process except this one.

    Used at the top of each loop iteration to guarantee a clean slate -
    no leftover chart_app.py windows holding onto ports 8051-8056 from
    a previous run. See the module-level WARNING above before running
    this on a shared machine.
    """
    current_pid = os.getpid()
    for proc in psutil.process_iter(["pid", "name"]):
        try:
            if proc.info["name"] and "python" in proc.info["name"].lower():
                if proc.info["pid"] != current_pid:
                    proc.kill()
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue


if __name__ == "__main__":
    # Path to the 1-minute candle file generated by setup_data.py
    CHART_DATA_PATH = "data/xauusd_1min.csv"
    # Path to the file that accumulates every labeling decision you make
    MY_DATA_PATH = "my_data.csv"

    # Load chart reference data (the full candle history to sample from)
    df_charts = pd.read_csv(CHART_DATA_PATH)

    # --- INITIALIZE THE MODEL ONCE BEFORE THE LOOP ---
    # Automatically creates model_dir/ if missing, and otherwise loads
    # the existing model weights, optimizer state, and feature
    # normalizer state from disk so training picks up where it left off.
    agent = OnlineModelAgent(model_dir="model_dir")

    while True:
        kill_other_python_processes()

        # Pick a random candle to center this batch's 6 chart windows on.
        # (Minimum 300 so the largest lookback window - 300 candles back
        # - always has enough history behind it.)
        random_number = random.randint(300, df_charts["candle_number"].size)

        # Manager dict shared across the 6 child processes so each chart
        # window can report its Buy/Neutral/Sell decision back to main.py.
        manager = multiprocessing.Manager()
        trade_feedback = manager.dict()

        # (start_candle, end_candle, port) for each of the 6 lookback windows.
        # end_candle is always random_number; start_candle varies to give
        # 300/200/100/50/20/10-candle views of the same decision point.
        frame_configs = [
            (random_number - 300, random_number, 8051),
            (random_number - 200, random_number, 8052),
            (random_number - 100, random_number, 8053),
            (random_number - 50, random_number, 8054),
            (random_number - 20, random_number, 8055),
            (random_number - 10, random_number, 8056),
        ]

        print(f"\n--- New Batch for Candle: {random_number} ---")
        print("Launching 6 concurrent windows simultaneously...")

        active_processes = []
        for start, end, port in frame_configs:
            p = multiprocessing.Process(
                target=show_candles,
                args=(df_charts, start, end, port, trade_feedback),
                daemon=True
            )
            p.start()
            active_processes.append(p)
            time.sleep(0.1)  # small stagger so browser tabs don't all fight to open at once

        # Block here until all 6 windows have reported a decision.
        while len(trade_feedback) < 6:
            time.sleep(0.5)

        print("All tabs handled. Appending decisions to my_data.csv...")

        # --- LOG STRING CODES BACK INTO THE MAIN TIMEFRAME COLUMNS ---
        # "neurall" (typo, intentionally kept) is the fallback default if
        # a window somehow didn't report - model_agent.py's LABEL_MAP
        # recognizes both "neurall" and the correctly-spelled "neutral"
        # as the same class, so this fallback stays safe either way.
        new_row = {
            'random_number': int(random_number),
            'f_300': str(trade_feedback.get(300, "neurall")),
            'f_200': str(trade_feedback.get(200, "neurall")),
            'f_100': str(trade_feedback.get(100, "neurall")),
            'f_50':  str(trade_feedback.get(50, "neurall")),
            'f_20':  str(trade_feedback.get(20, "neurall")),
            'f_10':  str(trade_feedback.get(10, "neurall"))
        }

        # Convert this single row to a mini DataFrame
        df_new = pd.DataFrame([new_row])

        # Check if the file is completely empty or doesn't exist yet to decide on headers
        file_is_empty = not os.path.exists(MY_DATA_PATH) or os.path.getsize(MY_DATA_PATH) == 0

        # Append directly to the text stream (safe against column alignment bugs)
        df_new.to_csv(MY_DATA_PATH, mode='a', header=file_is_empty, index=False)
        print(f"Successfully saved your choices to {MY_DATA_PATH}!")

        # Terminate windows immediately to clear port allocations for the next batch
        for p in active_processes:
            if p.is_alive():
                p.terminate()
                p.join()

                # --- MODEL INTEGRATION PIPELINE ---
                print("\n--- Model Evaluation & Training Session ---")

                human_choices = {int(k): str(v) for k, v in trade_feedback.items()}

                # Step 5: Generate live inference from current model architecture states.
                # This shows what the model *would have* predicted, for comparison
                # against your actual choice, before it trains on your choice below.
                live_predictions = agent.predict_batch(df_charts, random_number)
                print("---> Model System Current Live Predictions:")
                for tf in [300, 200, 100, 50, 20, 10]:
                    print(
                        f"  * Timeframe Lookback {tf:3d}: Prediction -> {live_predictions[tf]:<8} | Your Choice -> {human_choices.get(tf, 'neurall')}")

                # Step 6 & 7: Train the model on your human-labeled decision for
                # this batch, and auto-save the updated model to disk.
                loss_val = agent.update_model(df_charts, random_number, human_choices)
                print(f"---> Online Gradient Loss: {loss_val:.4f} | Model updated and auto-saved successfully.")

        input_text = input("\nEnter '0' to quit, or press Enter to run another batch: ")
        if input_text == "0":
            break

    print("Done!")
